[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = true 

[[language]]
name = "typescript"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
config = { format = { "semicolons" = "insert", "insertSpaceBeforeFunctionParenthesis" = false } }

[[language]]
name = "javascript"
auto-format = true
config = { format = { "semicolons" = "insert", "insertSpaceBeforeFunctionParenthesis" = false } }

[[language]]
name = "tsx"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
config = { format = { "semicolons" = "insert", "insertSpaceBeforeFunctionParenthesis" = false } }

[[language]]
name = "jsx"
auto-format = true
config = { format = { "semicolons" = "insert", "insertSpaceBeforeFunctionParenthesis" = false } }

[[language]]
name = "php"
auto-format = true

[[language]]
name = "python"
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true
