[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = {typescript = { tsdk = "/home/elvessousa/.npm-global/lib/node_modules/typescript/lib" }, environment = "node"}

[[language]]
name = "astro"
auto-format = true
language-servers = [ "astro-ls" ]

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = true 

[[language]]
name = "typescript"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "tsx"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "jsx"
auto-format = true

[[language]]
name = "php"
auto-format = true

[[language]]
name = "python"
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true
